### ISSUE TITLE
Mobile/touch disable

### ISSUE THREAD

**Issue by moondawg69** [lusaxweb/Kursor#1]
Nice work. Just wondering about how to disable in touch devices?

**Comment by luisDanielRoviraContreras** [comment]
I think the default library should not be in devices since the interaction with the mouse does not exist, in a next update we will add the queries media to solve this

Thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Ready and fix it and now only the element and animation in desktop is added and it will not be added in devices

Thank you very much for the contribution
